#!/bin/bash

awk '{print (NR>0 ? "chr" : "") $0}' $1 | awk '{$2=$2-1;print}' | sort -k1,1 -k2,2n > temp
NAME=`basename $1 | awk '{sub(/bed/,"fa");print}'`
>> $NAME
twoBitToFa http://hgdownload.cse.ucsc.edu/gbdb/hg19/hg19.2bit -bed=temp $NAME
rm temp
